server:
  port: 8080
  context-path: /
  session:
    cookie:
      path: /
      http-only: true
spring:

  # 默认开发环境 生产时指定环境 java -jar demo.jar --spring.profiles.active=prod
  profiles:
    active: dev
  # 使用caffeine本地缓存,开启缓存命中监控,15分钟过期,
  cache:
    type: caffeine
    caffeine:
      spec: recordStats,refreshAfterWrite=PT15M,maximumSize=30
  server:
    multipart:
      enabled: true
      maxFileSize: 10000MB
      maxRequestSize: 10000MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss.SSS
    time-zone: GMT+8
# mybatis配置
mybatis:
  type-aliases-package: com.varyuan.awesome.po
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 开启数据表字段自动下划线转驼峰
    map-underscore-to-camel-case: true