server:
  port: 8080
  servlet:
    context-path: /
    session:
      cookie:
        path: /
        http-only: true
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss.SSS
    time-zone: GMT+8
  # 默认开发环境 生产时指定环境 java -jar demo.jar --spring.profiles.active=prod
  profiles:
    active: dev
  # 使用caffeine本地缓存,开启缓存命中监控
  cache:
    type: caffeine
    caffeine:
      spec: recordStats
# mybatis配置
mybatis:
  type-aliases-package: com.varyuan.awesome.po
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 开启数据表字段自动下划线转驼峰
    map-underscore-to-camel-case: true