spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/yuan?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    # 池配置
    hikari:
      minimum-idle: 2
      maximum-pool-size: 4
      pool-name: yuan-dev
  redis:
    host: 172.25.222.112
    port: 6379
#    password: 123456
    database: 0 # 几号库
    lettuce:
      pool:
        max-active: 3 # 最大连接
        max-idle: 3 # 最大空闲连接
        min-idle: 0 # 最小空闲连接
        max-wait: 100ms # 连接等待时间
  # 默认开启缓存, ctrl+f9进行rebuild
  thymeleaf:
    cache: false
# 打印sql
logging:
  level:
    com.varyuan.awesome.dao: debug
